### ISSUE TITLE
Question about ChangeNotifierProvider<AuthService>

### ISSUE THREAD

**Issue by cargallo** [delay/flutter_firebase_auth_starter#2]
Hi there! First of all thanks for sharing the code. Actually I'm using the architecture explained by Andrea, but I found it very complicated in some parts so shearching arround I encountered your code. I have a doubt wich is why did you put ChangeNotifierProvider<AuthService> as a provider on main.dart if the class AuthService that extends ChangeNotifier doesn't fire any notifyListeners? Thanks in advance

**Comment by delay** [comment]
Yeah I found Andrea code in use on another project and only later found out he created it and then used the version he made.  Honestly I probably no longer need to use ChangeNotifierProvider.  I had changed a lot around in that code and at one time I was using notifyListeners. I probably could update using that.  Thanks for pointing it out.
