### ISSUE TITLE
when app first time start detects language but doesn't translate

### ISSUE THREAD

**Issue by 7ozonfol** [delay/flutter_firebase_auth_starter#3]
so, when app starts first time it detects whatever language the device is but doesn't translate, i have to close the app and run it again so how can i fix this?
also am really thankful to this code honestly saved me days of development for both language and auth specifically

**Comment by delay** [comment]
I recently made an update to the project so you can see if it helps.  If it doesn't, I am actually working on a new version of this project [here](https://github.com/delay/flutter_starter) which makes use of GetX a really nice package.
